SCALE Job started on Пт 17/03/2023 08:47:11
With Host name C49501
working directory C:\Users\user\AppData\Local\Temp\scale.user.1612
and process id 1612.
Input file named U:\Belin\_Рабочие_\Программирование\Python\VasDis\Origens\max_2_hours.inp
and output file named U:\Belin\_Рабочие_\Программирование\Python\VasDis\Origens\max_2_hours.out
##########################################################
